name: Link OG Data
version: 1.0.1
description: A tag & field type for obtaining and presenting meta tags
url: https://github.com/jrc9designstudio/statamic-link-og-data
developer: JRC9 Design Studio
developer_url: https://jrc9.ca

